routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});

Route::get('/', function () {
    return view('auth.login');
});

Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');


    /**
     * category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');

    });

    /**
     * fonts routs
     */
    Route::group(['namespace' => 'Fonts'], function(){
       Route::resource('fonts', 'FontController');
    });

    /**
     * keyboard routs
     */
    Route::group(['namespace' => 'Keyboard'], function(){
        Route::resource('keyboard', 'KeyboardController');
    });
});

app/Models/Keyboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Keyboard extends Model
{
    use SoftDeletes;

    protected $table = "keyboard";
}

app/Http/Controllers/Api/Keyboard/KeyboardController.php
<?php

namespace App\Http\Controllers\Api\Keyboard;

use App\Http\Controllers\Controller;
use App\Http\Resources\KeyboardResource;
use Illuminate\Http\Request;
use App\Models\Keyboard;
use Exception;

class KeyboardController extends Controller
{
    public function index(Request $request)
    {
        try {
            $category_id = ($request->category_id) ? $request->category_id : "";
            if ($category_id) {
                $keyboard = Keyboard::where('category_id', $category_id)->orderBy('created_at', 'DESC')->get();
            } else {
                $keyboard = Keyboard::orderBy('created_at', 'DESC')->get();
            }
            $keyboard = KeyboardResource::collection($keyboard);
            return response()->json(['data' => $keyboard], 200);
        } catch
        (Exception $e) {
            return response()->json(['data' => "Keyboard not found..."], 422);
        }
    }
}

app/Http/Controllers/Keyboard/KeyboardController.php
<?php

namespace App\Http\Controllers\Keyboard;

use App\Http\Controllers\Controller;
use App\Models\Keyboard;
use App\Traits\ImageTrait;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\Keyboard\KeyboardRequest;
use Exception;

class KeyboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keyboard = Keyboard::get();
        return view('pages.keyboard.index', compact('keyboard'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $keyboard = false;
        $category = Category::get();
        return view('pages.keyboard.create', compact('keyboard'), compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KeyboardRequest $request)
    {
//        dd($request);
        try {
            $file_font_image = ImageTrait::makeImage($request->file_font, 'keyboard/');
            $file_background_image = ImageTrait::makeImage($request->file_background, 'keyboard/');
            $file_keyboard_image = ImageTrait::makeImage($request->file_keyboard, 'keyboard/');

            $keyboard = new Keyboard;
            $keyboard->key_text_color = "#".str_replace('#', '', $request->key_text_color);
            $keyboard->background_alpha = $request->background_alpha;
            $keyboard->key_background_color = "#".str_replace('#', '',$request->key_background_color);
            $keyboard->file_font = $file_font_image;
            $keyboard->key_border_color = "#".str_replace('#', '', $request->key_border_color);
            $keyboard->file_background = $file_background_image;
            $keyboard->file_keyboard = $file_keyboard_image;
            $keyboard->category_id = $request->category_id;

            $keyboard->save();
            return redirect()->back()->with('success', 'Keyboard Added successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Keyboard not added...');
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Keyboard $keyboard)
    {
        $category = Category::get();
        return view('pages.keyboard.create', compact('keyboard'), compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KeyboardRequest $request, Keyboard $keyboard)
    {
        try {
            if ($request->hasFile('file_font')) {
                $file_font_image = ImageTrait::makeImage($request->file_font, 'keyboard/');

            } else {
                $file_font_image = $keyboard->file_font;
            }
            if ($request->hasFile('file_background')) {
                $file_background_image = ImageTrait::makeImage($request->file_background, 'keyboard/');
            } else {
                $file_background_image = $keyboard->file_background;
            }

            if ($request->hasFile('file_keyboard')) {
                $file_keyboard_image = ImageTrait::makeImage($request->file_keyboard, 'keyboard/');
            } else {
                $file_keyboard_image = $keyboard->file_keyboard;
            }

            $keyboard->key_text_color = "#".str_replace('#', '', $request->key_text_color);
            $keyboard->background_alpha = $request->background_alpha;
            $keyboard->key_background_color = "#".str_replace('#', '', $request->key_background_color);
            $keyboard->file_font = $file_font_image;
            $keyboard->key_border_color = "#".str_replace('#', '', $request->key_border_color);
            $keyboard->file_background = $file_background_image;
            $keyboard->file_keyboard = $file_keyboard_image;
            $keyboard->category_id = $request->category_id;

            $keyboard->save();
            return redirect()->back()->with('success', 'Keyboard Updated Successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Keyboard not Updated...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Keyboard $keyboard)
    {
        try {
            $keyboard->delete();
            return response()->json(['data' => 'Keyboard deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Keyboard not Deleted...', 'status' => '0']);
        }
    }
}

resources/views/pages/keyboard/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save Keyboard</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif
                        <form method="post" action="{{($keyboard) ? route('keyboard.update',$keyboard->id) : route('keyboard.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($keyboard)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Text color</label>
                                <input type="text" placeholder="Text color" name="key_text_color" class="form-control" value="{{($keyboard) ? $keyboard->key_text_color : old('key_text_color')}}">
                                @if ($errors->has('key_text_color'))
                                    <span class="text-danger">{{ $errors->first('key_text_color') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Background Alpha</label>
                                <input type="text" placeholder="Background Alpha" name="background_alpha" class="form-control" value="{{($keyboard) ? $keyboard->background_alpha : old('background_alpha')}}">
                                @if ($errors->has('background_alpha'))
                                    <span class="text-danger">{{ $errors->first('background_alpha') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Background Color</label>
                                <input type="text" placeholder="Background Color" name="key_background_color" class="form-control" value="{{($keyboard) ? $keyboard->key_background_color : old('key_background_color')}}">
                                @if ($errors->has('key_background_color'))
                                    <span class="text-danger">{{ $errors->first('key_background_color') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Font File ( ttf/otf file)</label>
                                <input type="file" placeholder="Font file" name="file_font" class="form-control" value="{{($keyboard) ? $keyboard->file_font : ""}}">
                                @if ($errors->has('file_font'))
                                    <span class="text-danger">{{ $errors->first('file_font') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Border Color</label>
                                <input type="text" placeholder="Border Color" name="key_border_color" class="form-control" value="{{($keyboard) ? $keyboard->key_border_color : old('key_border_color')}}">
                                @if ($errors->has('key_border_color'))
                                    <span class="text-danger">{{ $errors->first('key_border_color') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Background File</label>
                                <input type="file" placeholder="Background File" name="file_background" class="form-control" value="{{($keyboard) ? $keyboard->file_background : ""}}">
                                @if ($errors->has('file_background'))
                                    <span class="text-danger">{{ $errors->first('file_background') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Keyboard File</label>
                                <input type="file" placeholder="Background File" name="file_keyboard" class="form-control" value="{{($keyboard) ? $keyboard->file_keyboard : ""}}">
                                @if ($errors->has('file_keyboard'))
                                    <span class="text-danger">{{ $errors->first('file_keyboard') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Category</label>
                                <select class="form-control" name="category_id">
                                    <option value=""  disabled {{($keyboard) ? "" : "selected" }}> Select Category</option>
                                    @foreach($category as $ck=>$cv)
                                        <option value="{{$cv->id}}" {{ ($keyboard) ?  ($cv->id == $keyboard->category_id) ? "selected" : "" : ""}}>{{$cv->name}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('file_background'))
                                    <span class="text-danger">{{ $errors->first('file_background') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/keyboard/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-10">
                <h2>Keyboard</h2>
            </div>
            <div class="col-md-2">
                <a class="btn btn-lg form-control add-btn" href="{{ route('keyboard.create') }}">Create Keyboard</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Text Color</th>
                        <th>Background Alpha</th>
                        <th>Backgorund color</th>
                        <th>Font File</th>
                        <th>Keyboard Color</th>
                        <th>Background File</th>
                        <th>Keyboard File</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php
                        $i = 1;
                    @endphp
                    @foreach( $keyboard as $key => $val )
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$val->key_text_color}}</td>
                            <td>{{$val->background_alpha}}</td>
                            <td>{{$val->key_background_color}}</td>
                            <td>{{$val->file_font}}</td>
                            <td>{{$val->key_border_color}}</td>
                            <td><img src="{{ asset('storage/keyboard/'. $val->file_background)}}" width="100"></td>
                            <td><img src="{{ asset('storage/keyboard/'. $val->file_keyboard)}}" width="100"></td>
                            <td>
                                <a href="{{route('keyboard.edit',$val->id)}}" class="fa fa-edit action"></a>
                                <a class="fa fa-trash del-keyboard" data-id="{{$val->id}}"></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @if(Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger">{{ Session::get('error') }}</div>
    @endif

    <script type="text/javascript">
        var crawlapps_keyboard = {
            init: function () {
                this.keyboard_delete();
            },
            keyboard_delete: function () {
                $(document).on('click', '.del-keyboard', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this Keyboard...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('keyboard.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },
        };
        $(document).ready(function () {
            crawlapps_keyboard.init();
        });
    </script>
@endsection