routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});

Route::get('/', function () {
    return view('auth.login');
});

Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');


    /**
     * category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');

    });

    /**
     * fonts routs
     */
    Route::group(['namespace' => 'Fonts'], function(){
       Route::resource('fonts', 'FontController');
    });

    /**
     * keyboard routs
     */
    Route::group(['namespace' => 'Keyboard'], function(){
        Route::resource('keyboard', 'KeyboardController');
    });
});

app/Models/Font.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Font extends Model
{
    use SoftDeletes;

    protected $table = "fonts";
}

app/Http/Controllers/Api/Font/FontController.php
<?php

namespace App\Http\Controllers\Api\Font;

use App\Http\Controllers\Controller;
use App\Http\Resources\FontResource;
use App\Models\Font;
use Exception;
use Illuminate\Http\Request;

class FontController extends Controller
{
    public function index(){

        try {
            $font = Font::select('id','name','file_image','file_font')->orderBy('created_at', 'DESC')->get();
            $font = FontResource::collection($font);
            return response()->json(['data' => $font], 200);
        } catch
        (Exception $e) {
            return response()->json(['data' => "Font not found..."], 422);
        }
    }
}

app/Http/Controllers/Fonts/FontController.php
<?php

namespace App\Http\Controllers\Fonts;

use App\Http\Controllers\Controller;
use App\Http\Requests\Fonts\FontRequest;
use Illuminate\Http\Request;
use App\Models\Font;
use App\Traits\ImageTrait;

class FontController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // dd(config('filesystems.default'));
        $font = Font::get();
        return view('pages.fonts.index', compact('font'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $font = false;
        return view('pages.fonts.create', compact('font'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(FontRequest $request)
    {
        try {

            $image = ImageTrait::makeImage($request->image, 'images/');
            $fontfile = ImageTrait::makeImage($request->fontfile, 'fontfiles/');

            $font = new Font;
            $font->name = $request->name;
            $font->file_image = $image;
            $font->file_font = $fontfile;

            $font->save();
            return redirect()->back()->with('success', 'Font Added successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Font not added...');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Font $font)
    {
//        dd($font);
        return view('pages.fonts.create', compact('font'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(FontRequest $request, Font $font)
    {
//        dd($font);
        try {
            if ($request->hasFile('image')) {
                $image = ImageTrait::makeImage($request->image, 'images/');
            } else {
                $image = $font->file_image;
            }
            if ($request->hasFile('fontfile')) {
                $fontfile = ImageTrait::makeImage($request->fontfile, 'fontfiles/');
            } else {
                $fontfile = $font->file_font;
            }

            $font->name = $request->name;
            $font->file_image = $image;
            $font->file_font = $fontfile;
            $font->save();
            return redirect()->back()->with('success', 'Font Updated Successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Font not Updated...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public
    function destroy(Font $font)
    {
        try {
            $font->delete();
            return response()->json(['data' => 'Font deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Font not Deleted...', 'status' => '0']);

//            $e->getMessage();
        }
    }
}

resources/views/pages/fonts/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save Font</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif

                        <form method="post" action="{{ ($font) ? route('fonts.update',$font->id) : route('fonts.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($font)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Name</label>
                                <input type="text" placeholder="Font name" name="name" class="form-control" value="{{ ($font) ? $font->name : old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Image</label>
                                <input type="file" placeholder="Font Image" name="image" class="form-control" value="">
                                @if ($errors->has('image'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="form-control-label text-uppercase">File</label>
                                <input type="file" placeholder="Font File" name="fontfile" class="form-control" value="">
                                @if ($errors->has('fontfile'))
                                    <span class="text-danger">{{ $errors->first('fontfile') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/fonts/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-10">
                <h2>Font</h2>
            </div>
            <div class="col-md-2">
                <a class="btn btn-lg form-control add-btn" href="{{ route('fonts.create') }}">Create Font</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>File</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php
                        $i = 1;
                    @endphp
                    @foreach( $font as $key => $val )
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$val->name}}</td>
                            <td><img src="{{ asset('storage/images/'. $val->file_image)}}" width="100"></td>
                            <td>{{$val->file_font}}</td>
                            <td>
                                <a href="{{route('fonts.edit',$val->id)}}" class="fa fa-edit action"></a>
                                <a class="fa fa-trash del-font" data-id="{{$val->id}}"></a>

                            </td>
                        </tr>

                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @if(Session::has('success'))
        <div class="alert alert-success">{{ Session::get('success') }}</div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger">{{ Session::get('error') }}</div>
    @endif


    <script type="text/javascript">
        var crawlapps_keyboard = {
            init: function () {
                this.category_delete();
            },
            category_delete: function () {
                $(document).on('click', '.del-font', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this Font...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('fonts.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },
        };
        $(document).ready(function () {
            crawlapps_keyboard.init();
        });
    </script>
@endsection